version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ar-assets-stack"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
s3_prefix = "ar-assets-stack"
disable_rollback = true
image_repositories = []

parameter_overrides = "BucketAr=menu-assets-dev-833090513377 CfDomain=placeholder.cloudfront.net TableMenu=MenuTable-dev"

[default.global.parameters]
region = "ap-south-1"


