version = 0.1

[default.global.parameters]
stack_name = "ws-project"
region = "us-east-1"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "ws-project"
disable_rollback = true
parameter_overrides = "Stage=\"dev\""
image_repositories = []
